# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.network "public_network"

  config.vm.synced_folder "../tmp", "/opt/data"

  config.vm.provider "virtualbox" do |vb|
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
      vb.memory = "4096"
      vb.cpus= "4"
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y apache2 wget unzip
    systemctl start apache2
    systemctl enable apache2
    cd /tmp
    wget https://www.tooplate.com/zip-templates/2126_antique_cafe.zip
    unzip -o 2126_antique_cafe.zip
    cp -r 2126_antique_cafe/*  /var/www/html
    systemctl stop apache2
    clear
    history
  SHELL
end

